### ISSUE TITLE
Multi play

### ISSUE THREAD

**Issue by lucia116** [byWulf/threejs-dice#1]
Hello. 
Can i use multi play? 
For example, can multiple users see the same result?

**Comment by byWulf** [comment]
Hey,

the system is designed to archieve exactly that. But you have to implement it on your own.

Let the users connect to a server.
Let the server generate a random number.
Send this random number to all connected clients.
Let each client roll the number it got from the server.

If you are looking for a out-of-the-box tool, try the multiplayer version of teal: http://a.teall.info/mdice/
