### ISSUE TITLE
Adding walls to the rolling example

### ISSUE THREAD

**Issue by jadinm** [byWulf/threejs-dice#16]
First, thanks for the work, the examples already give nice results with a very few lines of code

I would like to reproduce the effect of http://a.teall.info/dice/ on my website with this library
The [rolling example](https://github.com/byWulf/threejs-dice/blob/master/examples/rolling.html) covers almost everything that I need

But I did not manage to add "walls" to prevent the dices from leaving the green area if they roll too far away

Do someone know how to do that ?

**Comment by jadinm** [comment]
Ok, so I managed to make one of the wall with

```js
// scene object for visualization
var wallMaterial = new THREE.MeshPhongMaterial( { color: '#0000aa', side: THREE.DoubleSide } );
var wallGeometry = new THREE.PlaneGeometry(30, 30, 10, 10);
var wall = new THREE.Mesh(wallGeometry, wallMaterial);
wall.rotation.y = Math.PI / 2;
wall.position.x = 15;
scene.add(wall);

// actual wall for cannon
var barrierBody = new CANNON.Body({mass: 0, shape: new CANNON.Plane(), material: DiceManager.barrierBodyMaterial});
barrierBody.quaternion.setFromAxisAngle(new CANNON.Vec3(0, 1, 0), -Math.PI / 2);
barrierBody.position.set(wall.position.x, wall.position.y, wall.position.z)
world.add(barrierBody);
```

But the second wall makes the roll completely wild.
The dices are shooted in a straight line very far away.

```js
// scene object for visualization
var wallMaterial2 = new THREE.MeshPhongMaterial( { color: '#aa00aa', side: THREE.DoubleSide } );
var wallGeometry2 = new THREE.PlaneGeometry(30, 30, 10, 10);
var wall2 = new THREE.Mesh(wallGeometry2, wallMaterial2);
wall2.rotation.z = Math.PI / 2;
wall2.position.z = 15;
scene.add(wall2);

// actual wall for cannon
var barrierBody2 = new CANNON.Body({mass: 0, shape: new CANNON.Plane(), material: DiceManager.barrierBodyMaterial});
barrierBody2.quaternion.setFromAxisAngle(new CANNON.Vec3(0, 0, 1), -Math.PI / 2);
barrierBody2.position.set(wall2.position.x, wall2.position.y, wall2.position.z)
world.add(barrierBody2);
```

Any idea why ?

**Comment by jbrecht** [comment]
where you have:
`wall2.rotation.z = Math.PI / 2;`

I think you want:
`wall2.rotation.y = Math.PI;`

then you'll want to make the corresponding change in the setFromAxisAngle argument.
`barrierBody2.quaternion.setFromAxisAngle(new CANNON.Vec3(0, 1, 0), -Math.PI);`

**Comment by jadinm** [comment]
Indeed, it works !
Thanks a lot ! :+1:
