### ISSUE TITLE
Migrating Geometry to BufferGeometry

### ISSUE THREAD

**Issue by Ragash** [byWulf/threejs-dice#19]
Hi guys!

i was trying to update three to 0.127 because old version's vulnerabilities.
Unluckily from 0.125 geometry and face3 are removed, do anyone succeded in migrating the geometry and faces to buffergeometry and indexes?

thanks in advance

**Comment by eipporko** [comment]
Hi, I just updated the source code to work with threejs 0.127 using BufferGeometries. 
I tested with my own project without using typescript and works as expected. 
Now I'm trying to test it within this project to make a pull request but I don't know how to run the examples, any idea?

**Comment by joeyshipley** [comment]
@eipporko, sorry I don't know much about converting it to Typescript. Your updates to using current THREE.js sounds amazing though, do you mind sharing the work you did to get your dependencies up to date and working with this?

**Comment by eipporko** [comment]
@joeyshipley now I'm on holidays and far away from my computer, but in a week I will do a pull request although I couldn't test it in this current project. I made an ES6 module and that's how I'm using it.

**Comment by joeyshipley** [comment]
No worries, appreciate the time when it's easy/no-stress. :)

**Comment by byWulf** [comment]
Please try it out, I just merged @eipporko 's PR.
